// Daggerheart Core Rulebook Items (Loot Section)
// This list should be expanded as needed for completeness.
import type { InventoryItem } from '../types/characterTypes';

export const coreItems: InventoryItem[] = [
    { name: 'Torch', source: 'core' },
    { name: '50 feet of rope', source: 'core' },
    { name: 'Basic supplies', source: 'core', notes: 'Bedroll, rations, flint, etc.' },
    { name: 'Handful of gold', source: 'core' },
    { name: 'Animal companion', source: 'core', notes: 'If class grants' },
    { name: 'Thieves’ tools', source: 'core' },
    { name: 'Whispering orb', source: 'core' },
    { name: 'Family heirloom', source: 'core' },
    { name: 'Book you’re trying to translate', source: 'core' },
    { name: 'Tiny harmless elemental pet', source: 'core' },
    { name: 'Shield', source: 'core' },
    { name: 'Bundle of offerings', source: 'core' },
    { name: 'Sigil of your god', source: 'core' },
    { name: 'Trophy from a past victory', source: 'core' },
    // Consumables and loot section items:
    { name: 'Healing Potion', source: 'core', type: 'consumable', notes: 'Restore HP or remove a condition' },
    { name: 'Antitoxin', source: 'core', type: 'consumable', notes: 'Cure poison' },
    { name: 'Rations (1 day)', source: 'core', type: 'consumable' },
    { name: 'Waterskin', source: 'core' },
    { name: 'Lantern', source: 'core' },
    { name: 'Oil Flask', source: 'core', type: 'consumable', notes: 'For lantern or fire' },
    { name: 'Grappling Hook', source: 'core' },
    { name: 'Lockpicks', source: 'core' },
    { name: 'Blanket', source: 'core' },
    { name: 'Tent', source: 'core' },
    { name: 'Fishing Tackle', source: 'core' },
    { name: 'Climbing Kit', source: 'core' },
    { name: 'Spyglass', source: 'core' },
    { name: 'Map', source: 'core' },
    { name: 'Compass', source: 'core' },
    { name: 'Ink & Quill', source: 'core' },
    { name: 'Journal', source: 'core' },
    { name: 'Musical Instrument', source: 'core' },
    { name: 'Disguise Kit', source: 'core' },
    { name: 'Alchemist’s Supplies', source: 'core' },
    { name: 'Herbalism Kit', source: 'core' },
    { name: 'Caltrops', source: 'core', type: 'consumable' },
    { name: 'Ball Bearings', source: 'core', type: 'consumable' },
    { name: 'Smoke Bomb', source: 'core', type: 'consumable' },
    { name: 'Rope Ladder', source: 'core' },
    { name: 'Crowbar', source: 'core' },
    { name: 'Hammer & Pitons', source: 'core' },
    { name: 'Chalk', source: 'core', type: 'consumable' },
    { name: 'Perfume', source: 'core', type: 'consumable' },
    { name: 'Fine Clothes', source: 'core' },
    { name: 'Common Clothes', source: 'core' },
    // Add more consumables from the core rules:
    { name: 'Fire Bomb', source: 'core', type: 'consumable', notes: 'Deals fire damage in an area' },
    { name: 'Flash Bomb', source: 'core', type: 'consumable', notes: 'Blinds or distracts enemies' },
    { name: 'Acid Vial', source: 'core', type: 'consumable', notes: 'Corrodes objects or deals acid damage' },
    { name: 'Poison Vial', source: 'core', type: 'consumable', notes: 'Poisons a weapon or target' },
    { name: 'Scroll of Recall', source: 'core', type: 'consumable', notes: 'Recall a spent domain card' },
    { name: 'Scroll of Healing', source: 'core', type: 'consumable', notes: 'Heals a target' },
    { name: 'Scroll of Protection', source: 'core', type: 'consumable', notes: 'Grants temporary protection' },
    { name: 'Bandages', source: 'core', type: 'consumable', notes: 'Stabilize wounds' },
    { name: 'Herbal Poultice', source: 'core', type: 'consumable', notes: 'Heals minor injuries' },
    { name: 'Magic Berry', source: 'core', type: 'consumable', notes: 'Restores a small amount of HP' },
    { name: 'Enchanted Cookie', source: 'core', type: 'consumable', notes: 'Provides a magical effect' },
    { name: 'Throwing Knife', source: 'core', type: 'consumable', notes: 'Single-use thrown weapon' },
    // Add more as needed from the full loot section
]; 